# Generated by Django 5.2.8 on 2025-12-01 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon_class', models.CharField(default='fa-recycle', help_text='FontAwesome class (e.g., fa-laptop)', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WasteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the item')),
                ('specifications', models.TextField(blank=True, help_text='Technical specs (e.g., Weight: 5kg, Purity: 99%)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in KES', max_digits=12)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(choices=[('new', 'New / Surplus'), ('refurbished', 'Refurbished / Grade A'), ('used', 'Used / Good'), ('scrap', 'Scrap / Recyclable')], default='used', max_length=20)),
                ('location', models.CharField(default='Nairobi, Industrial Area', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('is_verified_seller', models.BooleanField(default=False)),
                ('is_flash_sale', models.BooleanField(default=False)),
                ('co2_saved_kg', models.FloatField(default=0.0, verbose_name='CO2 Saved (kg)')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='marketplace.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
