# Generated by Django 5.2.8 on 2025-12-03 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_seller_profiles(apps, schema_editor):
    """
    Pre-create SellerProfile rows for existing Users referenced by WasteItem
    with matching primary keys so existing seller_id values remain valid
    when FK switches to SellerProfile.
    """
    User = apps.get_model('auth', 'User')
    WasteItem = apps.get_model('marketplace', 'WasteItem')
    SellerProfile = apps.get_model('marketplace', 'SellerProfile')
    db_alias = schema_editor.connection.alias

    user_ids = (
        WasteItem.objects.using(db_alias)
        .values_list('seller_id', flat=True)
        .distinct()
    )
    for uid in user_ids:
        try:
            user = User.objects.using(db_alias).get(pk=uid)
        except User.DoesNotExist:
            continue
        # Create SellerProfile with the same PK as the user id to satisfy FK
        # Only if not already existing
        if not SellerProfile.objects.using(db_alias).filter(pk=uid).exists():
            SellerProfile.objects.using(db_alias).create(
                id=uid,
                user=user,
                business_name=user.username,
                is_verified=False,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_wasteitem_stock_quantity_buyerprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyerprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sellerprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(seed_seller_profiles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='wasteitem',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.sellerprofile'),
        ),
    ]
