# Generated by Django 5.2.8 on 2025-12-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_buyerprofile_user_sellerprofile_and_more'),
    ]

    operations = [
    ]
