# Generated by Django 5.2.8 on 2025-12-03 17:44

from django.db import migrations


def forwards_func(apps, schema_editor):
    """
    Create SellerProfile for users referenced by existing WasteItems and
    remap WasteItem.seller to point to SellerProfile ids.
    """
    User = apps.get_model('auth', 'User')
    WasteItem = apps.get_model('marketplace', 'WasteItem')
    SellerProfile = apps.get_model('marketplace', 'SellerProfile')
    db_alias = schema_editor.connection.alias

    # Collect distinct current seller ids (these are User ids from pre-change data)
    user_ids = (
        WasteItem.objects.using(db_alias)
        .values_list('seller_id', flat=True)
        .distinct()
    )

    # Ensure a SellerProfile exists for each referenced user
    for uid in user_ids:
        try:
            user = User.objects.using(db_alias).get(pk=uid)
        except User.DoesNotExist:
            continue
        SellerProfile.objects.using(db_alias).get_or_create(
            user=user,
            defaults={'business_name': user.username}
        )

    # Remap each WasteItem.seller to the corresponding SellerProfile id
    for item in WasteItem.objects.using(db_alias).all():
        uid = item.seller_id  # currently points to User id in legacy rows
        try:
            seller_profile = SellerProfile.objects.using(db_alias).get(user_id=uid)
        except SellerProfile.DoesNotExist:
            continue
        # Assign FK to SellerProfile id
        item.seller_id = seller_profile.id
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        # Depends on schema change that introduced SellerProfile and altered WasteItem.seller FK
        ('marketplace', '0005_alter_buyerprofile_user_sellerprofile_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
