# Generated by Django 5.2.8 on 2025-12-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_fix_seller_data_final'),
    ]

    operations = [
    ]
