# Generated by Django 5.2.8 on 2025-12-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_data_migration_for_sellers'),
        ('marketplace', '0008_fix_seller_data_final'),
    ]

    operations = [
    ]
