# Generated by Django 5.2.8 on 2025-12-09 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_order_order_uuid_transaction_checkout_request_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='payment_number',
            field=models.CharField(blank=True, help_text='M-Pesa number for receiving payments', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('order', 'checkout_request_id'), name='uniq_order_checkout_tx'),
        ),
    ]
