# Generated by Django 5.2.8 on 2025-12-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_notification_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='sub_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
