# Generated by Django 5.2.8 on 2025-12-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_buyerprofile_county_buyerprofile_sub_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteitem',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wasteitem',
            name='sub_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
