# Generated by Django 5.2.8 on 2025-12-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_wasteitem_county_wasteitem_sub_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, help_text='M-Pesa Receipt Number (e.g. QKH1234567)', max_length=50, null=True),
        ),
    ]
