# Generated by Django 5.2.8 on 2025-12-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_contactmessage_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='description',
            field=models.TextField(blank=True, help_text='About the seller'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_profiles/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='sub_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
