# Generated by Django 5.2.8 on 2025-12-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_sellerprofile_county_sellerprofile_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('same_county_fee', models.DecimalField(decimal_places=2, default=200.0, help_text='Fee when buyer and seller are in the same county', max_digits=10)),
                ('different_county_fee', models.DecimalField(decimal_places=2, default=500.0, help_text='Fee when buyer and seller are in different counties', max_digits=10)),
                ('standard_fee', models.DecimalField(decimal_places=2, default=300.0, help_text='Default fee when location is unknown', max_digits=10)),
            ],
            options={
                'verbose_name': 'Shipping Configuration',
                'verbose_name_plural': 'Shipping Configuration',
            },
        ),
    ]
