# Generated by Django 5.2.8 on 2026-01-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupstation',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=200.0, help_text='Cost to ship to this station', max_digits=10),
        ),
    ]
